
require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.1
  SuggestExtensions: false
    
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*.rb'
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec/factories/**/*.rb'
Layout/LineLength:
  Exclude:
    - '**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'
Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/schema.rb'