
AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.2.1
  SuggestExtensions: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
