baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Pervenche'
archetypeDir = 'hugo/archetype'
assetDir = 'hugo/assets'
dataDir = 'hugo/data'
contentDir = 'hugo/content'
themesDir = 'hugo/theme'
layoutDir = 'hugo/layouts'