name: GitHub Pages

on:
  push:
    branches:
      - master # Set a branch to deploy
    paths:
      - ./hugo/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          extended: true

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Assets precompile
        env:
          GOOGLE_CLIENT_ID: "."
          GOOGLE_CLIENT_SECRET: "."
        run: bundle exec rake assets:precompile --trace

      - name: Move the css file to hugo/static/css
        run: |
          find ./public/assets -type f -iname "application-*.css" | while read line; do
              echo "Copying '$line' to /hugo/static/css"
              cp -- "$line" hugo/static/css/application.css
          done

      - name: Remove files from public/assets
        run: rm -rf ./public/assets

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/www
